/* This file is automatically generated by configure */
/* DO NOT EDIT MANUALLY */

#ifndef CONFIG_H
#define CONFIG_H


#define SCUMM_LITTLE_ENDIAN
#undef SCUMM_BIG_ENDIAN
#define SCUMM_64BITS
#undef SCUMM_NEED_ALIGNMENT
#undef USE_ELF_LOADER
#undef DYNAMIC_MODULES
#define USE_MT32EMU
#define USE_RGB_COLOR
#define USE_SAVEGAME_TIMESTAMP
#define USE_SCALERS
#define USE_HQ_SCALERS
#define USE_VORBIS
#undef USE_TREMOR
#define USE_FLAC
#define USE_MAD
#undef USE_ALSA
#undef USE_JPEG
#undef USE_PNG
#undef USE_THEORADEC
#undef USE_FAAD
#define USE_SEQ_MIDI
#undef USE_SNDIO
#define USE_TIMIDITY
#define USE_ZLIB
#undef USE_MPEG2
#undef USE_FLUIDSYNTH
#undef USE_READLINE
#undef USE_TEXT_CONSOLE_FOR_DEBUGGER
#undef USE_TASKBAR_UNITY
#undef USE_FREETYPE2
#define USE_OPENGL
#undef USE_GLES
#undef USE_NASM
#undef ENABLE_VKEYBD
#undef ENABLE_KEYMAPPER
#define ENABLE_EVENTRECORDER
#define USE_TRANSLATION
#define USE_DETECTLANG
#define USE_TASKBAR
#define USE_BINK
#undef USE_UPDATES
/* #define TAINTED_BUILD */

/* Data types */
typedef unsigned char byte;
typedef unsigned int uint;
typedef unsigned char uint8;
typedef unsigned short uint16;
typedef unsigned int uint32;
typedef signed char int8;
typedef signed short int16;
typedef signed int int32;

/* 64-bit stuff */
typedef signed long int64;
#if defined(__APPLE__) && !defined(__ppc__)
#ifndef _UINT64
#define _UINT64
typedef unsigned long uint64;
#endif
#else
typedef unsigned long uint64;
#endif

#endif /* CONFIG_H */
